language: node_js
sudo: false
node_js:
- '0.10'
env:
  global:
  - secure: GLh1QHZDG6OkAV6PuHlqTymmSUK8syAmIpt6hH7tG1x16NyijcEy4ktcSNg8E5H2EcR/2AnlnkphXl7/6HesywVSPSw5kEq0mKI19AI9G9IgzccN0DAvh/JCHYvL4mHhEM+t9IZXp6OsLXAPPW364mmVnbpLxQ4SeQPw5Ie7/8Q=
  - secure: p4H/K31mfBa1nodh4l154iQSty6o/Ku6s39E6rLwuM/lVCqsgAU6p/9zzL4GDgB7PKWj7lGtgw14jJR/2eWvWoNMAmElUJpr783JlQUztwAZpjI5vIjEAIz690/qc4CG41dmXT8bAuLT90cnyNxcjY/Mqyab4Dcu3YnhcLesXbs=
