language: node_js
script:
- npm test
- npm run browser-test-ff
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
sudo: false
node_js:
- '0.12'
- '4'
env:
  global:
    secure: s5Gkl8zV18XJabPnvrxAsPLNG0S3NN9Jn8t+x9bkygnUJ+iZNsXoblHXDlikPMCwySIa6mOSCVWsuSQJvxJqJMV1QYwiMRE/ljkt7BP9+jAC4L/13yjAVHVhmiOd6dBX70rwKSJ2W5eGmpl5XO6aLqLaUjDUIZFMkZm8YhtfCow=
