language: node_js
sudo: false
node_js:
- '0.10'
env:
  global:
  - secure: DPPQd38yi4xZVJXi2273HshEYU3NGM6TBwGnEeGfGKW6DoC5BLNUHx+1wm8FxkridTcJ06Mb8A9pXmVm+MN9kbtytcerERV9dvp8+ATD9FJgaaX+d968/fh1vC6DO5dGZk+sQFMzn4XHYnrGN68IyaCnYRyFIgrosFYQpEdx+AY=
  - secure: Fr2V0A0131xmPzvU9IWwjfElqnguY0aGcyApbLYbcKEiB/yyNptkYpo5pCyGBeWJI6A57jOlqkj8+rAJHnnOyWQThH78J2XuQB9tvsODVMRio9ew4umUO8tGc6MJzc4Qv+Zm3IrPXFYE72O2OGGHcV622mlrNwnzqOQ9WRR+8LY=
