language: node_js
sudo: false
node_js:
- '0.10'
env:
  global:
  - secure: YN0kzlicFGAz9VadCC0kJKPf1fuOqX9voqgj4NnzqldxOEPSzOMrh78rYtHkBMnaweQTeGRtIoXmuhWVK676KDYVrwFv5woBcvnMWKLCnwHypVWHRpRmCduc+dZnroGyENuLYptgTHuczcMrzrIqk/AIX6O9qF96HkGDlC2IiRQ=
  - secure: HQu4JFrD6gC8MWJEQSDBKLa6BtlmMcecLt31PoKk7vdoXnpPIWQYa1TUKslsQuBxZxEPnvjAnJQoLVDKh/mBq9VPnFyS7+pxSWLqc49sW2fyVweTjSHzHBY2PwH7Qsz3e6hZQ6abRkOwWiUozUQRd7zjG6AYhVU/Fqf3xuDtoXM=
